trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'de4b18c3-e631-40a9-bab2-22ecfa65c319'
  webAppName: 'hexaware-java'

steps:
- task: Maven@4
  displayName: 'Maven Package'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: CopyFiles@2
  displayName: 'Copy WAR to staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish WAR as artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy WAR to Azure Linux Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    WebAppName: $(webAppName)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.war'
    RuntimeStack: 'TOMCAT|9.0-java17'
    DeploymentTypeLinux: 'oneDeploy'
